### PR TITLE
Add OpauthPageController with canView extension point to fix #28

### LINKED ISSUE #28: Site wide view restrictions block the OpauthController
If a Site has "Who can view pages on this site?" set to anything other than "Anyone" the OpauthController fails the `ContentController::init()` permission check on line 109.

A fix for this appears to be hard setting the access of the `OpauthController`'s `$dataRecord` like so:

``` php
    /**
     * Fake a Page_Controller by using that class as a failover
     */
    public function __construct($dataRecord = null) {
        if(class_exists('Page_Controller')) {
            $dataRecord = new Page_Controller($dataRecord);
            //Force the canView of page to avoid issue with site-wide access restrictions
            $dataRecord->dataRecord->CanViewType = 'Anyone';
        }
        parent::__construct($dataRecord);
    }
```

I'll keep testing but are there any security concerns stemming from this?

### PR DESCRIPTION
**Pull request by stephenmcm**

### CODE REVIEW

**Comment by willmorgan** [comment]
Would it be possible to add some tests for this? ;)

**Comment by dhensby** [comment]
@willmorgan think this is worth pursuing / doing ourselves or closing?

**Comment by willmorgan** [comment]
I can pick this up.

**Comment by willmorgan** [comment]
Superseded by #35

**Pull request closed without merging**
